Fixed dumping of Controller proto message
If mController is not null, then "dumpsys activity --proto processes"
will cause the following exception

Exception occurred while dumping:
java.lang.IllegalArgumentException: Attempt to call write(long, String) with
   Message tag=37 fieldId=0x10b00000025

Bug: 135941071
Test: adb shell am monitor
      and run "adb shell dumpsys activity --proto processes" in another window
Change-Id: Ic476f09654b56e72172dd6ae03d19d775269de89