Disable TAPL rotation checks
The check is unstable and frequently lead to an error

```
java.lang.AssertionError: http://go/tapl test failure: Unexpected display rotation expected: 1 but was: 0;
Context: want to switch to home, performed action to switch to Home - swiping up to home, want to get workspace object; now visible state is Workspace; displayId: 0

```

Fixes: 434759129
Test: atest WMShellFlickerServicePlatinumTests
Flag: TEST_ONLY
Change-Id: Id4345d4768cc71fc9d675cf76f1b8d3e006170e7